config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :events
  resources :attendees_events, only: [:create]
  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendees_event.rb
class AttendeesEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendees_events, foreign_key: "event_id"
    has_many :atendees, through: :attendees_events, source: :user
    belongs_to :creator, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :attendees_events, foreign_key: "user_id"
  has_many :attending_events, through: :attendees_events, source: :event

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/User/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/attendees_events_controller.rb
class AttendeesEventsController < ApplicationController
    before_action :authenticate_user!
    def create
        @event = Event.find(params[:event_id])
        puts "HIIIIIIIIIIIIIIIIIIIIIIIII #{@event}"
        @attendee = AttendeesEvent.new(event_id: @event.id, user_id: current_user.id)
        if @attendee.save
            redirect_to event_path(@event)
        else
            flash[:alert] = "Uh oh..."
            redirect_to @event
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new()
    end

    def create
        
        @event = current_user.created_events.build(event_params)
        puts "EVENTS CERATOR IS #{@event.creator}"
        if (@event.save)
            redirect_to @event
        else
            render :new
        end
    end
    

    private

    def event_params
        params.require(:event).permit(:event_name, :event_location, :event_date)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(current_user.id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1>Current Events</h1>
<div class="events-index-container">
        <% @events.each do |event|%>
            <%= link_to event, class: "event-info-container" do%>
                <div class="event-info">
                    <div class="event-info-header">
                        <div class="event-name-text"><%=event.event_name%></div>
                    </div>
                    <div class="event-info-body">
                        <div class="event-date-text"><%=event.event_date%></div>
                        <div class="event-location-text"><%=event.event_location%></div>
                    </div>
                </div>
            <%end%>
        <%end%>
</div>

app/views/events/new.html.erb
<%= form_with model: @event do |form|%>

    <p><%= @event.errors.full_messages %></p>


    <div class="event_name">
        <%= form.label :event_name %>
        <%= form.text_area :event_name %>

    </div>

    <div class="event_location">
        <%= form.label :event_location %>
        <%= form.text_area :event_location %>
    </div>

    <div class="event_date">
        <%= form.label :event_date %>
        <%= form.date_select :event_date %>
    </div>

    <div class="event_submit">
        <%=form.submit%>
    </div>

<%end%>

app/views/events/show.html.erb
<p>Event Creator: <%=@event.creator.first_name%> <%=@event.creator.last_name%></p>
<p><%=@event.event_name%></p>
<p><%=@event.event_location%></p>
<p><%=@event.event_date%></p>

<%if current_user%>
    <%if current_user.attending_events.exists?(@event.id)%>
        <p>You're attending this event!</p>
    <%else%>
        <p><%=link_to "Click here to attend!", attendees_events_path(event_id: @event.id), method: :post%></p>
    <%end%>
<%else%>
    <p><%=link_to "Click here to attend!", attendees_events_path(event_id: @event.id), method: :post%></p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="flex-container-justified-center">
      <nav class="nav-bar">
          <div class="nav-item-container">
            <%= link_to 'Home', root_path%>
            <%= link_to 'Create An Event!', new_event_path%>
          </div>

          <%if current_user%>
            <div class="nav-item-container">
              <%= link_to 'My Events', user_path(current_user)%>
              <%= link_to 'Log Out', destroy_user_session_path, method: :delete%>
            </div>
          <%else%>
            <div class="nav-item-container">
              <%= link_to 'Sign In', new_user_session_path%>
              <%= link_to 'Sign Up', new_user_registration_path%>
            </div>
          <%end%>
      </nav>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>

<div class="attendings-events-container">
    <h3>Events you're attending:</h3>
    <% @user.attending_events.each do |event|%>

        <p><%=event.event_name%></p>

    <%end%>
</div>

<div class="create-events-container">
    <h3>Your created events:</h3>
    <% @user.created_events.each do |event|%>

        <p><%=event.event_name%></p>

    <%end%>
</div>